version: '3.9'
services:
  db: # main db
    image: mongo
    restart: always
    ports:
      - 27017:27017
#    volumes:
#      - mongodb:/data/db
    env_file: 
      - ./.env

  admin_panel: # admin panel
    image: mongo-express
    ports:
      - 8081:8081
    env_file:
      - ./.env
    
    depends_on:
      - db


#volumes:
#  mongodb:
